version: '3.8'
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8-community
    restart: always
    privileged: true
    user: root
    volumes:
      - /home/sgcan_prueba/archivos/sonarqube:/otp/sonarqube
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_USERNAME: admin
      SONARQUBE_PASSWORD: admin
    networks:
      - net
networks:
  net:
    name: networks_jenkins