version: '3.9'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: always
    volumes:
      - D:\DATOS\jenkins_home:/var/jenkins_home
    ports:
      - "9080:8080"
    environment:
      SONARQUBE_USERNAME: admin
      SONARQUBE_PASSWORD: admin
    networks:
      - net
networks:
  net:
    name: networks_jenkins